### ISSUE TITLE
Pre-built binaries for linux?

### ISSUE THREAD

**Issue by sarathsi** [cdwfs/img2ktx#4]
Hi, 
Is there pre-built binaries for linux?
I do not see in the Releases page (https://github.com/cdwfs/img2ktx/releases)
Thank you.

**Comment by cdwfs** [comment]
There are not; sorry. I do not currently have access to a Linux system upon which to build/test it (though when I did earlier this year, everything worked fine). If you run into any problems building the tool yourself, please file additional issues and I'd be happy to help you through them.
